language: node_js
node_js:
  - "0.10"
before_install:
  - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
  - "sudo apt-get update -qq"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "sudo apt-get install -qq gcc-4.8 g++-4.8"
  - "sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90"
  - "npm install"

env:
  - CHROME_BIN=/usr/bin/chromium-browser

script: node_modules/.bin/gulp build && npm test

notifications:
  email:
    - videos5@corp.globo.com
